---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    app.quarkus.io/commit-id: 10e84afee1ed1fb6bc4329c297b6513387ff8524
    app.quarkus.io/vcs-url: https://github.com/LeonardoBonacci/time-is-up.git
    app.quarkus.io/build-timestamp: 2020-11-28 - 18:04:06 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: timesup-react-home-gate
    app.kubernetes.io/version: "4.2"
  name: timesup-react-home-gate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    app.quarkus.io/commit-id: 10e84afee1ed1fb6bc4329c297b6513387ff8524
    app.quarkus.io/vcs-url: https://github.com/LeonardoBonacci/time-is-up.git
    app.quarkus.io/build-timestamp: 2020-11-28 - 18:04:06 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: timesup-react-home-gate
    app.kubernetes.io/version: "4.2"
  name: timesup-react-home-gate
spec:
  ports:
  - name: http
    nodePort: 30003
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: timesup-react-home-gate
    app.kubernetes.io/version: "4.2"
  type: NodePort
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    app.quarkus.io/commit-id: 10e84afee1ed1fb6bc4329c297b6513387ff8524
    app.quarkus.io/vcs-url: https://github.com/LeonardoBonacci/time-is-up.git
    app.quarkus.io/build-timestamp: 2020-11-28 - 18:04:06 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: timesup-react-home-gate
    app.kubernetes.io/version: "4.2"
  name: timesup-react-home-gate-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
- kind: ServiceAccount
  name: timesup-react-home-gate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    app.quarkus.io/commit-id: 10e84afee1ed1fb6bc4329c297b6513387ff8524
    app.quarkus.io/vcs-url: https://github.com/LeonardoBonacci/time-is-up.git
    app.quarkus.io/build-timestamp: 2020-11-28 - 18:04:06 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: timesup-react-home-gate
    app.kubernetes.io/version: "4.2"
  name: timesup-react-home-gate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: timesup-react-home-gate
      app.kubernetes.io/version: "4.2"
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        app.quarkus.io/commit-id: 10e84afee1ed1fb6bc4329c297b6513387ff8524
        app.quarkus.io/vcs-url: https://github.com/LeonardoBonacci/time-is-up.git
        app.quarkus.io/build-timestamp: 2020-11-28 - 18:04:06 +0000
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: timesup-react-home-gate
        app.kubernetes.io/version: "4.2"
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: kafka-config
        image: leonardobonacci/timesup-react-home-gate:4.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: timesup-react-home-gate
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccount: timesup-react-home-gate
