apiVersion: v1
kind: Service
metadata:
  name: tile38
spec:
  selector:
    app: tile38
  ports:
    - name: tile38
      port: 9851
      targetPort: 9851
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tile38
  labels:
    app: tile38
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tile38
  template:
    metadata:
      labels:
        app: tile38
    spec:
      containers:
      - name: tile38
        image: tile38/tile38:latest
        ports:
        - containerPort: 9851
